name = "private-folio15"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"
assets = { directory = "dist", binding = "ASSETS" }

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[define]
__dirname = "'/'"
"process.env" = "{}"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "0f0b63bf-62c4-45b0-980a-5c44833768ad" # Placeholder for local dev
